"""Pydantic models, grouped by role.

`api` holds the HTTP request/response bodies, `llm_schemas` the structured
output the LLM emits, `views` the internal projections read out of storage,
and `common` the leaf pieces the other three share.  This package re-exports
all of them so `from .models import X` keeps working from anywhere.
"""

from __future__ import annotations

# `gossipmemo.models` used to be a single module; these imported names were
# part of its namespace, so they stay importable from it.
from datetime import datetime as datetime
from datetime import timezone as timezone
from typing import Any as Any
from typing import Literal as Literal

from pydantic import BaseModel as BaseModel
from pydantic import ConfigDict as ConfigDict
from pydantic import Field as Field
from pydantic import field_validator as field_validator

from .api import (
    HealthResponse,
    ManualMemoryRequest,
    MergePersonRequest,
    MergePersonResponse,
    MessageInput,
    QueryRequest,
    QueryResponse,
    QueueStatus,
    RetractRequest,
    SourceRef,
    SupersedeRequest,
    TurnRequest,
    TurnResponse,
)
from .common import (
    COVERAGE_CRITERIA,
    COVERAGE_ROOTS,
    CoverageEntryStatus,
    HypothesisConfidence,
    HypothesisEvidence,
    HypothesisEvidenceRole,
    HypothesisOwnerKind,
    HypothesisStatus,
    LearningGoalStatus,
    MemoryBasis,
    MemoryKind,
    utc_now,
)
from .llm_schemas import (
    ContinuityReasoningResult,
    ExtractedCoverageAudit,
    ExtractedCoverageEntry,
    ExtractedCoverageEntryEdit,
    ExtractedMemory,
    ExtractedOwnerEvidenceDigest,
    ExtractedOwnerEvidenceDigestItem,
    ExtractedPerson,
    ExtractedRelationship,
    ExtractionResult,
    GoalClosureRecommendation,
    GoalPlanningCandidates,
    GoalPlanningResult,
    HypothesisActions,
    HypothesisTransition,
    HypothesisUpsert,
    InferredMemory,
    InferredMemoryActions,
    InferredMemoryRetraction,
    LearningGoalCandidate,
    LearningGoalTransition,
    LearningGoalUpsert,
    PersonProjectionResult,
    PersonReasoningResult,
    ReasoningActionsResult,
    RelationshipProjectionResult,
    RelationshipReasoningResult,
    UserModelReasoningResult,
    UserReasoningActionsResult,
)
from .views import (
    ContextBundle,
    ContinuityView,
    CoverageEntryView,
    CoverageRootView,
    GuidanceBundle,
    GuidanceItem,
    HypothesisView,
    LearningGoalView,
    MemoryView,
    ModelMessage,
    OwnerEvidenceDigestView,
    PersonSummaryView,
    PersonView,
    QueryContext,
    RelationshipView,
    UserModelView,
)

__all__ = [
    "COVERAGE_CRITERIA",
    "COVERAGE_ROOTS",
    "ContextBundle",
    "ContinuityReasoningResult",
    "ContinuityView",
    "CoverageEntryStatus",
    "CoverageEntryView",
    "CoverageRootView",
    "ExtractedCoverageAudit",
    "ExtractedCoverageEntry",
    "ExtractedCoverageEntryEdit",
    "ExtractedMemory",
    "ExtractedOwnerEvidenceDigest",
    "ExtractedOwnerEvidenceDigestItem",
    "ExtractedPerson",
    "ExtractedRelationship",
    "ExtractionResult",
    "GoalClosureRecommendation",
    "GoalPlanningCandidates",
    "GoalPlanningResult",
    "GuidanceBundle",
    "GuidanceItem",
    "HealthResponse",
    "HypothesisActions",
    "HypothesisConfidence",
    "HypothesisEvidence",
    "HypothesisEvidenceRole",
    "HypothesisOwnerKind",
    "HypothesisStatus",
    "HypothesisTransition",
    "HypothesisUpsert",
    "HypothesisView",
    "InferredMemory",
    "InferredMemoryActions",
    "InferredMemoryRetraction",
    "LearningGoalCandidate",
    "LearningGoalStatus",
    "LearningGoalTransition",
    "LearningGoalUpsert",
    "LearningGoalView",
    "ManualMemoryRequest",
    "MemoryBasis",
    "MemoryKind",
    "MemoryView",
    "MergePersonRequest",
    "MergePersonResponse",
    "MessageInput",
    "ModelMessage",
    "OwnerEvidenceDigestView",
    "PersonProjectionResult",
    "PersonReasoningResult",
    "PersonSummaryView",
    "PersonView",
    "QueryContext",
    "QueryRequest",
    "QueryResponse",
    "QueueStatus",
    "ReasoningActionsResult",
    "RelationshipProjectionResult",
    "RelationshipReasoningResult",
    "RelationshipView",
    "RetractRequest",
    "SourceRef",
    "SupersedeRequest",
    "TurnRequest",
    "TurnResponse",
    "UserModelReasoningResult",
    "UserModelView",
    "UserReasoningActionsResult",
    "utc_now",
]
